create extension if not exists pgcrypto;

create table if not exists public.breeder_sites (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  slug text not null,
  template_id text not null check (template_id in ('heritage', 'modern-meadow', 'signature')),
  config jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint breeder_sites_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint breeder_sites_owner_slug_unique unique (owner_id, slug)
);

create index if not exists breeder_sites_owner_id_idx on public.breeder_sites(owner_id);

create table if not exists public.published_breeder_sites (
  site_id uuid primary key references public.breeder_sites(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  slug text not null unique,
  template_id text not null check (template_id in ('heritage', 'modern-meadow', 'signature')),
  config jsonb not null,
  published_at timestamptz not null default now()
);

create index if not exists published_breeder_sites_owner_id_idx on public.published_breeder_sites(owner_id);

create table if not exists public.breeder_site_versions (
  id bigint generated by default as identity primary key,
  site_id uuid not null references public.breeder_sites(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  version_number integer not null,
  source text not null check (source in ('manual', 'ai')),
  generation_id uuid,
  config jsonb not null,
  created_at timestamptz not null default now(),
  constraint breeder_site_versions_site_version_unique unique (site_id, version_number)
);

create index if not exists breeder_site_versions_owner_id_idx on public.breeder_site_versions(owner_id);
create index if not exists breeder_site_versions_site_id_idx on public.breeder_site_versions(site_id);

create table if not exists public.ai_site_generations (
  id uuid primary key default gen_random_uuid(),
  site_id uuid references public.breeder_sites(id) on delete set null,
  owner_id uuid not null references auth.users(id) on delete cascade,
  prompt text not null,
  model text not null,
  status text not null check (status in ('pending', 'complete', 'failed')),
  result jsonb,
  token_usage jsonb,
  error_code text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists ai_site_generations_owner_id_idx on public.ai_site_generations(owner_id);
create index if not exists ai_site_generations_site_id_idx on public.ai_site_generations(site_id);

alter table public.breeder_site_versions
  add constraint breeder_site_versions_generation_id_fkey
  foreign key (generation_id) references public.ai_site_generations(id) on delete set null;

create or replace function public.set_breeder_site_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_breeder_site_updated_at on public.breeder_sites;
create trigger set_breeder_site_updated_at
before update on public.breeder_sites
for each row execute function public.set_breeder_site_updated_at();

alter table public.breeder_sites enable row level security;
alter table public.published_breeder_sites enable row level security;
alter table public.breeder_site_versions enable row level security;
alter table public.ai_site_generations enable row level security;

revoke all on public.breeder_sites from anon, authenticated;
revoke all on public.published_breeder_sites from anon, authenticated;
revoke all on public.breeder_site_versions from anon, authenticated;
revoke all on public.ai_site_generations from anon, authenticated;

grant select, insert, update, delete on public.breeder_sites to authenticated;
grant select on public.published_breeder_sites to anon;
grant select, insert, update, delete on public.published_breeder_sites to authenticated;
grant select, insert on public.breeder_site_versions to authenticated;
grant usage, select on sequence public.breeder_site_versions_id_seq to authenticated;
grant select, insert, update on public.ai_site_generations to authenticated;

create policy "Breeders can view their sites"
on public.breeder_sites for select to authenticated
using ((select auth.uid()) = owner_id);

create policy "Breeders can create their sites"
on public.breeder_sites for insert to authenticated
with check ((select auth.uid()) = owner_id);

create policy "Breeders can update their sites"
on public.breeder_sites for update to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "Breeders can delete their sites"
on public.breeder_sites for delete to authenticated
using ((select auth.uid()) = owner_id);

create policy "Published sites are publicly viewable"
on public.published_breeder_sites for select to anon, authenticated
using (true);

create policy "Breeders can publish their sites"
on public.published_breeder_sites for insert to authenticated
with check ((select auth.uid()) = owner_id);

create policy "Breeders can update their published sites"
on public.published_breeder_sites for update to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "Breeders can unpublish their sites"
on public.published_breeder_sites for delete to authenticated
using ((select auth.uid()) = owner_id);

create policy "Breeders can view their site versions"
on public.breeder_site_versions for select to authenticated
using ((select auth.uid()) = owner_id);

create policy "Breeders can create their site versions"
on public.breeder_site_versions for insert to authenticated
with check ((select auth.uid()) = owner_id);

create policy "Breeders can view their AI generations"
on public.ai_site_generations for select to authenticated
using ((select auth.uid()) = owner_id);

create policy "Breeders can create their AI generations"
on public.ai_site_generations for insert to authenticated
with check ((select auth.uid()) = owner_id);

create policy "Breeders can update their AI generations"
on public.ai_site_generations for update to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

